import type { Metadata } from "next";
import { JetBrains_Mono  } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Akshay Singh",
  description: "Generated by create next app",
};

const jetbrains_mono = JetBrains_Mono({
  weight: ["100", "200", "300", "400", "500", "600"]
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en ">
      <body
        className={` antialiased dark ${jetbrains_mono.className}`}
      >
        {children}
      </body>
    </html>
  );
}
